[package]
name = "fast-cache-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[features]
default = []
unsafe = ["fast-cache/unsafe"]

[dependencies]
fast-cache = { path = ".." }
libfuzzer-sys = "0.4"

[[bin]]
name = "embedded_command_sequence"
path = "fuzz_targets/embedded_command_sequence.rs"
test = false
doc = false
bench = false

[workspace]
