use serde::Serialize;

#[derive(Debug, Clone, Default, Serialize)]
pub struct TierStatsSnapshot {
    pub name: &'static str,
    pub len: usize,
    pub capacity: usize,
    pub hits: u64,
    pub misses: u64,
    pub promotions: u64,
    pub demotions: u64,
    pub evictions: u64,
    pub expirations: u64,
}

#[derive(Debug, Clone, Default, Serialize)]
pub struct ShardStatsSnapshot {
    pub shard_id: usize,
    pub key_count: usize,
    pub reads: u64,
    pub writes: u64,
    pub deletes: u64,
    pub expired: u64,
    pub maintenance_runs: u64,
    pub hot: TierStatsSnapshot,
    pub warm: TierStatsSnapshot,
    pub cold: TierStatsSnapshot,
    pub object_overflow: ObjectOverflowStatsSnapshot,
}

#[derive(Debug, Clone, Default, Serialize)]
pub struct ObjectOverflowStatsSnapshot {
    pub enabled: bool,
    pub backend: String,
    pub degraded: bool,
    pub queue_capacity: usize,
    pub queue_depth: usize,
    pub pending_jobs: usize,
    pub active_workers: usize,
    pub worker_threads: usize,
    pub remote_entries: usize,
    pub remote_value_bytes: usize,
    pub remote_stored_bytes: usize,
    pub offload_attempts: u64,
    pub offload_successes: u64,
    pub offload_failures: u64,
    pub offload_hot_skips: u64,
    pub fault_attempts: u64,
    pub fault_successes: u64,
    pub fault_failures: u64,
    pub checksum_failures: u64,
    pub remote_delete_attempts: u64,
    pub remote_delete_failures: u64,
    pub encode_ops: u64,
    pub compress_ops: u64,
    pub upload_ops: u64,
    pub download_ops: u64,
    pub decode_ops: u64,
    pub delete_ops: u64,
    pub retries: u64,
    pub timeouts: u64,
    pub auth_config_failures: u64,
    pub unavailable_failures: u64,
    pub integrity_failures: u64,
    pub not_found_failures: u64,
    pub delete_failures: u64,
    pub cleanup_scans: u64,
    pub cleanup_deletes: u64,
    pub object_bytes_raw: u64,
    pub object_bytes_stored: u64,
    pub encode_latency_us: u64,
    pub upload_latency_us: u64,
    pub download_latency_us: u64,
    pub decode_latency_us: u64,
    pub delete_latency_us: u64,
}

#[derive(Debug, Clone, Default, Serialize)]
pub struct WalStatsSnapshot {
    pub enabled: bool,
    pub blocks_merged: u64,
    pub entries_written: u64,
    pub segments_rotated: u64,
    pub bytes_written: u64,
    pub last_flush_ms: u64,
    pub recoveries: u64,
    pub snapshots_written: u64,
    pub tcp_export_enabled: bool,
    pub tcp_export_frames_queued: u64,
    pub tcp_export_frames_sent: u64,
    pub tcp_export_bytes_sent: u64,
    pub tcp_export_frames_dropped: u64,
    pub tcp_export_connect_failures: u64,
    pub tcp_export_write_failures: u64,
    pub tcp_export_active_subscribers: usize,
    pub tcp_export_subscribers_accepted: u64,
    pub tcp_export_subscribers_rejected: u64,
}

#[derive(Debug, Clone, Default, Serialize)]
pub struct GlobalStatsSnapshot {
    pub uptime_ms: u64,
    pub shard_count: usize,
    pub total_keys: usize,
    pub total_reads: u64,
    pub total_writes: u64,
    pub total_deletes: u64,
    pub total_expired: u64,
    pub shards: Vec<ShardStatsSnapshot>,
    pub wal: WalStatsSnapshot,
}
