use super::frame::*;
use crate::commands::redis::RedisCommand;
use crate::commands::{
    append::Append, auth::Auth, blmpop::BLMPop, blpop::BLPop, brpop::BRPop, bzmpop::BZMPop,
    bzpopmax::BZPopMax, bzpopmin::BZPopMin, client::Client, command::CommandInfo, config::Config,
    dbsize::DbSize, decr::Decr, decrby::DecrBy, dump::Dump, echo::Echo, expiretime::ExpireTime,
    flush, getdel::GetDel, getrange::GetRange, getset::GetSet, hdel::HDel, hello::Hello,
    hexists::HExists, hget::HGet, hgetall::HGetAll, hincrby::HIncrBy, hincrbyfloat::HIncrByFloat,
    hkeys::HKeys, hlen::HLen, hmget::HMGet, hrandfield::HRandField, hscan::HScan, hset::HSet,
    hsetnx::HSetNx, hvals::HVals, incr::Incr, incrby::IncrBy, incrbyfloat::IncrByFloat, info::Info,
    keys::Keys, lindex::LIndex, linsert::LInsert, llen::LLen, lmpop::LMPop, lpop::LPop,
    lpush::LPush, lpushx::LPushX, lrange::LRange, lrem::LRem, lset::LSet, ltrim::LTrim,
    memory::Memory, mget::MGet, mset::MSet, msetnx::MSetNx, pexpiretime::PExpireTime, ping::Ping,
    quit::Quit, restore::Restore, rpop::RPop, rpush::RPush, rpushx::RPushX, sadd::SAdd, scan::Scan,
    scard::SCard, sdiff::SDiff, sdiffstore::SDiffStore, select::Select, setrange::SetRange,
    sinter::SInter, sinterstore::SInterStore, sismember::SIsMember, smembers::SMembers,
    smismember::SMIsMember, smove::SMove, spop::SPop, srandmember::SRandMember, srem::SRem,
    sscan::SScan, strlen::StrLen, sunion::SUnion, sunionstore::SUnionStore, time::Time,
    type_cmd::Type as TypeCommand, zadd::ZAdd, zcard::ZCard, zcount::ZCount, zdiff::ZDiff,
    zdiffstore::ZDiffStore, zincrby::ZIncrBy, zinter::ZInter, zintercard::ZInterCard,
    zinterstore::ZInterStore, zlexcount::ZLexCount, zmpop::ZMPop, zmscore::ZMScore,
    zpopmax::ZPopMax, zpopmin::ZPopMin, zrandmember::ZRandMember, zrange::ZRange,
    zrangebylex::ZRangeByLex, zrangebyscore::ZRangeByScore, zrangestore::ZRangeStore, zrank::ZRank,
    zrem::ZRem, zremrangebylex::ZRemRangeByLex, zremrangebyrank::ZRemRangeByRank,
    zremrangebyscore::ZRemRangeByScore, zrevrange::ZRevRange, zrevrangebylex::ZRevRangeByLex,
    zrevrangebyscore::ZRevRangeByScore, zrevrank::ZRevRank, zscan::ZScan, zscore::ZScore,
    zunion::ZUnion, zunionstore::ZUnionStore,
};
use crate::protocol::Frame;
use crate::storage::EmbeddedStore;

pub(super) fn dispatch(name: &str, store: &EmbeddedStore, args: &[&[u8]]) -> Frame {
    match name {
        "PING" => Ping::execute(store, args),
        "AUTH" => Auth::execute(store, args),
        "SELECT" => Select::execute(store, args),
        "CLIENT" => Client::execute(store, args),
        "CONFIG" => Config::execute(store, args),
        "COMMAND" => CommandInfo::execute(store, args),
        "HELLO" => Hello::execute(store, args),
        "QUIT" => Quit::execute(store, args),
        "ECHO" => Echo::execute(store, args),
        "DBSIZE" => DbSize::execute(store, args),
        "FLUSHDB" => flush::FlushDb::execute(store, args),
        "FLUSHALL" => flush::FlushAll::execute(store, args),
        "TIME" => Time::execute(store, args),
        "INFO" => Info::execute(store, args),
        "MEMORY" => Memory::execute(store, args),
        "TYPE" => TypeCommand::execute(store, args),
        "KEYS" => Keys::execute(store, args),
        "SCAN" => Scan::execute(store, args),
        "DUMP" => Dump::execute(store, args),
        "RESTORE" => Restore::execute(store, args),
        "EXPIRETIME" => ExpireTime::execute(store, args),
        "PEXPIRETIME" => PExpireTime::execute(store, args),
        "APPEND" => Append::execute(store, args),
        "STRLEN" => StrLen::execute(store, args),
        "GETRANGE" => GetRange::execute(store, args),
        "SETRANGE" => SetRange::execute(store, args),
        "GETSET" => GetSet::execute(store, args),
        "GETDEL" => GetDel::execute(store, args),
        "INCR" => Incr::execute(store, args),
        "INCRBY" => IncrBy::execute(store, args),
        "DECR" => Decr::execute(store, args),
        "DECRBY" => DecrBy::execute(store, args),
        "INCRBYFLOAT" => IncrByFloat::execute(store, args),
        "MSET" => MSet::execute(store, args),
        "MGET" => MGet::execute(store, args),
        "MSETNX" => MSetNx::execute(store, args),
        "HSET" => HSet::execute(store, args),
        "HGET" => HGet::execute(store, args),
        "HMGET" => HMGet::execute(store, args),
        "HLEN" => HLen::execute(store, args),
        "HEXISTS" => HExists::execute(store, args),
        "HSETNX" => HSetNx::execute(store, args),
        "HINCRBY" => HIncrBy::execute(store, args),
        "HINCRBYFLOAT" => HIncrByFloat::execute(store, args),
        "HKEYS" => HKeys::execute(store, args),
        "HVALS" => HVals::execute(store, args),
        "HGETALL" => HGetAll::execute(store, args),
        "HSCAN" => HScan::execute(store, args),
        "HRANDFIELD" => HRandField::execute(store, args),
        "HDEL" => HDel::execute(store, args),
        "LPUSH" => LPush::execute(store, args),
        "RPUSH" => RPush::execute(store, args),
        "LPUSHX" => LPushX::execute(store, args),
        "RPUSHX" => RPushX::execute(store, args),
        "LRANGE" => LRange::execute(store, args),
        "LLEN" => LLen::execute(store, args),
        "LINDEX" => LIndex::execute(store, args),
        "LSET" => LSet::execute(store, args),
        "LREM" => LRem::execute(store, args),
        "LINSERT" => LInsert::execute(store, args),
        "LTRIM" => LTrim::execute(store, args),
        "LPOP" => LPop::execute(store, args),
        "RPOP" => RPop::execute(store, args),
        "BLPOP" => BLPop::execute(store, args),
        "BRPOP" => BRPop::execute(store, args),
        "LMPOP" => LMPop::execute(store, args),
        "BLMPOP" => BLMPop::execute(store, args),
        "SADD" => SAdd::execute(store, args),
        "SISMEMBER" => SIsMember::execute(store, args),
        "SMISMEMBER" => SMIsMember::execute(store, args),
        "SCARD" => SCard::execute(store, args),
        "SMEMBERS" => SMembers::execute(store, args),
        "SUNION" => SUnion::execute(store, args),
        "SINTER" => SInter::execute(store, args),
        "SDIFF" => SDiff::execute(store, args),
        "SUNIONSTORE" => SUnionStore::execute(store, args),
        "SINTERSTORE" => SInterStore::execute(store, args),
        "SDIFFSTORE" => SDiffStore::execute(store, args),
        "SMOVE" => SMove::execute(store, args),
        "SREM" => SRem::execute(store, args),
        "SSCAN" => SScan::execute(store, args),
        "SRANDMEMBER" => SRandMember::execute(store, args),
        "SPOP" => SPop::execute(store, args),
        "ZADD" => ZAdd::execute(store, args),
        "ZSCORE" => ZScore::execute(store, args),
        "ZMSCORE" => ZMScore::execute(store, args),
        "ZCARD" => ZCard::execute(store, args),
        "ZUNION" => ZUnion::execute(store, args),
        "ZINTER" => ZInter::execute(store, args),
        "ZDIFF" => ZDiff::execute(store, args),
        "ZINTERCARD" => ZInterCard::execute(store, args),
        "ZRANDMEMBER" => ZRandMember::execute(store, args),
        "ZRANGE" => ZRange::execute(store, args),
        "ZRANGEBYSCORE" => ZRangeByScore::execute(store, args),
        "ZREVRANGE" => ZRevRange::execute(store, args),
        "ZREVRANGEBYSCORE" => ZRevRangeByScore::execute(store, args),
        "ZRANGEBYLEX" => ZRangeByLex::execute(store, args),
        "ZREVRANGEBYLEX" => ZRevRangeByLex::execute(store, args),
        "ZLEXCOUNT" => ZLexCount::execute(store, args),
        "ZINCRBY" => ZIncrBy::execute(store, args),
        "ZCOUNT" => ZCount::execute(store, args),
        "ZRANK" => ZRank::execute(store, args),
        "ZREVRANK" => ZRevRank::execute(store, args),
        "ZPOPMIN" => ZPopMin::execute(store, args),
        "ZPOPMAX" => ZPopMax::execute(store, args),
        "ZMPOP" => ZMPop::execute(store, args),
        "ZREM" => ZRem::execute(store, args),
        "ZREMRANGEBYRANK" => ZRemRangeByRank::execute(store, args),
        "ZREMRANGEBYSCORE" => ZRemRangeByScore::execute(store, args),
        "ZREMRANGEBYLEX" => ZRemRangeByLex::execute(store, args),
        "ZSCAN" => ZScan::execute(store, args),
        "ZRANGESTORE" => ZRangeStore::execute(store, args),
        "ZUNIONSTORE" => ZUnionStore::execute(store, args),
        "ZINTERSTORE" => ZInterStore::execute(store, args),
        "ZDIFFSTORE" => ZDiffStore::execute(store, args),
        "BZPOPMIN" => BZPopMin::execute(store, args),
        "BZPOPMAX" => BZPopMax::execute(store, args),
        "BZMPOP" => BZMPop::execute(store, args),
        _ => error("ERR unsupported command"),
    }
}

pub(super) fn route_key_for_name<'a>(name: &str, first: Option<&'a [u8]>) -> Option<&'a [u8]> {
    match name {
        "PING" | "AUTH" | "HELLO" | "SELECT" | "QUIT" | "ECHO" | "COMMAND" | "CONFIG"
        | "CLIENT" | "DBSIZE" | "TIME" | "INFO" | "MEMORY" | "SCAN" | "RANDOMKEY" | "FLUSHDB"
        | "FLUSHALL" => None,
        _ => first,
    }
}
