use std::collections::BTreeSet;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum CoverageStatus {
    Supported,
    Missing,
}

#[derive(Debug, Clone, Copy)]
struct CommandCoverage {
    command: &'static str,
    status: CoverageStatus,
}

const TIER1_COMMANDS: &[&str] = &[
    "PING",
    "AUTH",
    "HELLO",
    "SELECT",
    "QUIT",
    "CLIENT GETNAME",
    "CLIENT SETNAME",
    "CLIENT ID",
    "CLIENT LIST",
    "CLIENT KILL",
    "GET",
    "SET",
    "DEL",
    "UNLINK",
    "EXISTS",
    "EXPIRE",
    "EXPIREAT",
    "EXPIRETIME",
    "PEXPIRE",
    "PEXPIREAT",
    "PEXPIRETIME",
    "TTL",
    "PTTL",
    "PERSIST",
    "TYPE",
    "TOUCH",
    "KEYS",
    "SCAN",
    "RENAME",
    "RENAMENX",
    "RANDOMKEY",
    "COPY",
    "DUMP",
    "RESTORE",
    "OBJECT ENCODING",
    "GETSET",
    "SETNX",
    "SETEX",
    "PSETEX",
    "MGET",
    "MSET",
    "MSETNX",
    "INCR",
    "DECR",
    "INCRBY",
    "DECRBY",
    "INCRBYFLOAT",
    "APPEND",
    "STRLEN",
    "GETRANGE",
    "SETRANGE",
    "GETBIT",
    "SETBIT",
    "BITCOUNT",
    "BITOP",
    "BITPOS",
    "BITFIELD",
    "GETDEL",
    "GETEX",
    "HSET",
    "HGET",
    "HMSET",
    "HMGET",
    "HGETALL",
    "HDEL",
    "HEXISTS",
    "HKEYS",
    "HVALS",
    "HLEN",
    "HINCRBY",
    "HINCRBYFLOAT",
    "HSCAN",
    "HSETNX",
    "HSTRLEN",
    "HRANDFIELD",
    "LPUSH",
    "RPUSH",
    "LPOP",
    "RPOP",
    "LRANGE",
    "LLEN",
    "LINDEX",
    "LSET",
    "LREM",
    "LTRIM",
    "LINSERT",
    "LPUSHX",
    "RPUSHX",
    "BLPOP",
    "BRPOP",
    "RPOPLPUSH",
    "LMOVE",
    "BLMOVE",
    "LMPOP",
    "BLMPOP",
    "SADD",
    "SREM",
    "SMEMBERS",
    "SISMEMBER",
    "SMISMEMBER",
    "SCARD",
    "SPOP",
    "SRANDMEMBER",
    "SUNION",
    "SINTER",
    "SDIFF",
    "SUNIONSTORE",
    "SINTERSTORE",
    "SDIFFSTORE",
    "SSCAN",
    "SMOVE",
    "ZADD",
    "ZREM",
    "ZSCORE",
    "ZINCRBY",
    "ZRANGE",
    "ZRANGEBYSCORE",
    "ZRANGEBYLEX",
    "ZREVRANGE",
    "ZREVRANGEBYSCORE",
    "ZREVRANGEBYLEX",
    "ZREMRANGEBYRANK",
    "ZREMRANGEBYSCORE",
    "ZREMRANGEBYLEX",
    "ZRANK",
    "ZREVRANK",
    "ZCARD",
    "ZCOUNT",
    "ZLEXCOUNT",
    "ZPOPMIN",
    "ZPOPMAX",
    "BZPOPMIN",
    "BZPOPMAX",
    "ZRANGESTORE",
    "ZSCAN",
    "ZMSCORE",
    "ZUNION",
    "ZINTER",
    "ZDIFF",
    "ZINTERCARD",
    "ZRANDMEMBER",
    "ZMPOP",
    "BZMPOP",
    "ZUNIONSTORE",
    "ZINTERSTORE",
    "ZDIFFSTORE",
    "MULTI",
    "EXEC",
    "DISCARD",
    "WATCH",
    "UNWATCH",
    "INFO",
    "COMMAND",
    "COMMAND COUNT",
    "COMMAND LIST",
    "COMMAND INFO",
    "COMMAND GETKEYS",
    "COMMAND GETKEYSANDFLAGS",
    "COMMAND DOCS",
    "COMMAND HELP",
    "CONFIG GET",
    "DBSIZE",
    "FLUSHDB",
    "FLUSHALL",
    "MEMORY USAGE",
    "TIME",
    "ECHO",
];

const COVERAGE: &[CommandCoverage] = &[
    supported("PING"),
    supported("AUTH"),
    supported("HELLO"),
    supported("SELECT"),
    supported("QUIT"),
    supported("CLIENT GETNAME"),
    supported("CLIENT SETNAME"),
    supported("CLIENT ID"),
    supported("CLIENT LIST"),
    supported("CLIENT KILL"),
    supported("GET"),
    supported("SET"),
    supported("DEL"),
    supported("UNLINK"),
    supported("EXISTS"),
    supported("EXPIRE"),
    supported("EXPIREAT"),
    supported("EXPIRETIME"),
    supported("PEXPIRE"),
    supported("PEXPIREAT"),
    supported("PEXPIRETIME"),
    supported("TTL"),
    supported("PTTL"),
    supported("PERSIST"),
    supported("TYPE"),
    supported("TOUCH"),
    supported("KEYS"),
    supported("SCAN"),
    supported("RENAME"),
    supported("RENAMENX"),
    supported("RANDOMKEY"),
    supported("COPY"),
    supported("DUMP"),
    supported("RESTORE"),
    supported("OBJECT ENCODING"),
    supported("GETSET"),
    supported("SETNX"),
    supported("SETEX"),
    supported("PSETEX"),
    supported("MGET"),
    supported("MSET"),
    supported("MSETNX"),
    supported("INCR"),
    supported("DECR"),
    supported("INCRBY"),
    supported("DECRBY"),
    supported("INCRBYFLOAT"),
    supported("APPEND"),
    supported("STRLEN"),
    supported("GETRANGE"),
    supported("SETRANGE"),
    supported("GETBIT"),
    supported("SETBIT"),
    supported("BITCOUNT"),
    supported("BITOP"),
    supported("BITPOS"),
    supported("BITFIELD"),
    supported("GETDEL"),
    supported("GETEX"),
    supported("HSET"),
    supported("HGET"),
    supported("HMSET"),
    supported("HMGET"),
    supported("HGETALL"),
    supported("HDEL"),
    supported("HEXISTS"),
    supported("HKEYS"),
    supported("HVALS"),
    supported("HLEN"),
    supported("HINCRBY"),
    supported("HINCRBYFLOAT"),
    supported("HSCAN"),
    supported("HSETNX"),
    supported("HSTRLEN"),
    supported("HRANDFIELD"),
    supported("LPUSH"),
    supported("RPUSH"),
    supported("LPOP"),
    supported("RPOP"),
    supported("LRANGE"),
    supported("LLEN"),
    supported("LINDEX"),
    supported("LSET"),
    supported("LREM"),
    supported("LTRIM"),
    supported("LINSERT"),
    supported("LPUSHX"),
    supported("RPUSHX"),
    supported("BLPOP"),
    supported("BRPOP"),
    supported("RPOPLPUSH"),
    supported("LMOVE"),
    supported("BLMOVE"),
    supported("LMPOP"),
    supported("BLMPOP"),
    supported("SADD"),
    supported("SREM"),
    supported("SMEMBERS"),
    supported("SISMEMBER"),
    supported("SMISMEMBER"),
    supported("SCARD"),
    supported("SPOP"),
    supported("SRANDMEMBER"),
    supported("SUNION"),
    supported("SINTER"),
    supported("SDIFF"),
    supported("SUNIONSTORE"),
    supported("SINTERSTORE"),
    supported("SDIFFSTORE"),
    supported("SSCAN"),
    supported("SMOVE"),
    supported("ZADD"),
    supported("ZREM"),
    supported("ZSCORE"),
    supported("ZINCRBY"),
    supported("ZRANGE"),
    supported("ZRANGEBYSCORE"),
    supported("ZRANGEBYLEX"),
    supported("ZREVRANGE"),
    supported("ZREVRANGEBYSCORE"),
    supported("ZREVRANGEBYLEX"),
    supported("ZREMRANGEBYRANK"),
    supported("ZREMRANGEBYSCORE"),
    supported("ZREMRANGEBYLEX"),
    supported("ZRANK"),
    supported("ZREVRANK"),
    supported("ZCARD"),
    supported("ZCOUNT"),
    supported("ZLEXCOUNT"),
    supported("ZPOPMIN"),
    supported("ZPOPMAX"),
    supported("BZPOPMIN"),
    supported("BZPOPMAX"),
    supported("ZRANGESTORE"),
    supported("ZSCAN"),
    supported("ZMSCORE"),
    supported("ZUNION"),
    supported("ZINTER"),
    supported("ZDIFF"),
    supported("ZINTERCARD"),
    supported("ZRANDMEMBER"),
    supported("ZMPOP"),
    supported("BZMPOP"),
    supported("ZUNIONSTORE"),
    supported("ZINTERSTORE"),
    supported("ZDIFFSTORE"),
    supported("MULTI"),
    supported("EXEC"),
    supported("DISCARD"),
    supported("WATCH"),
    supported("UNWATCH"),
    supported("INFO"),
    supported("COMMAND"),
    supported("COMMAND COUNT"),
    supported("COMMAND LIST"),
    supported("COMMAND INFO"),
    supported("COMMAND GETKEYS"),
    supported("COMMAND GETKEYSANDFLAGS"),
    supported("COMMAND DOCS"),
    supported("COMMAND HELP"),
    supported("CONFIG GET"),
    supported("DBSIZE"),
    supported("FLUSHDB"),
    supported("FLUSHALL"),
    supported("MEMORY USAGE"),
    supported("TIME"),
    supported("ECHO"),
];

const fn supported(command: &'static str) -> CommandCoverage {
    CommandCoverage {
        command,
        status: CoverageStatus::Supported,
    }
}

#[test]
fn tier1_commands_have_explicit_coverage_status() {
    let expected = TIER1_COMMANDS.iter().copied().collect::<BTreeSet<_>>();
    let actual = COVERAGE
        .iter()
        .map(|entry| entry.command)
        .collect::<BTreeSet<_>>();

    let missing = expected.difference(&actual).copied().collect::<Vec<_>>();
    let extra = actual.difference(&expected).copied().collect::<Vec<_>>();
    assert!(missing.is_empty(), "commands missing coverage: {missing:?}");
    assert!(
        extra.is_empty(),
        "coverage entries not in tier1 list: {extra:?}"
    );
    assert_eq!(
        COVERAGE.len(),
        actual.len(),
        "coverage list contains duplicate commands"
    );
}

#[test]
fn tier1_coverage_counts_are_intentional() {
    let supported = COVERAGE
        .iter()
        .filter(|entry| entry.status == CoverageStatus::Supported)
        .count();
    let missing = COVERAGE
        .iter()
        .filter(|entry| entry.status == CoverageStatus::Missing)
        .count();

    assert_eq!(supported, 167);
    assert_eq!(missing, 0);
}
