use super::{EnabledModuleInfo, RedisModuleCommand};

pub(super) const MODULES: &[EnabledModuleInfo] = &[EnabledModuleInfo {
    name: "redis-roaring",
    version: 1,
}];

pub(super) const COMMANDS: &[RedisModuleCommand] = redis_module_commands![
    "Redis-roaring";
    "R.APPENDINTARRAY" => true,
    "R.BITCOUNT" => false,
    "R.BITOP" => true,
    "R.BITPOS" => false,
    "R.CLEAR" => true,
    "R.CLEARBITS" => true,
    "R.CONTAINS" => false,
    "R.DELETEINTARRAY" => true,
    "R.DIFF" => false,
    "R.GETBIT" => false,
    "R.GETBITARRAY" => false,
    "R.GETBITS" => false,
    "R.GETINTARRAY" => false,
    "R.JACCARD" => false,
    "R.MAX" => false,
    "R.MIN" => false,
    "R.OPTIMIZE" => true,
    "R.RANGEINTARRAY" => false,
    "R.SETBIT" => true,
    "R.SETBITARRAY" => true,
    "R.SETFULL" => true,
    "R.SETINTARRAY" => true,
    "R.SETRANGE" => true,
    "R.STAT" => false,
    "R64.APPENDINTARRAY" => true,
    "R64.BITCOUNT" => false,
    "R64.BITOP" => true,
    "R64.BITPOS" => false,
    "R64.CLEAR" => true,
    "R64.CLEARBITS" => true,
    "R64.CONTAINS" => false,
    "R64.DELETEINTARRAY" => true,
    "R64.DIFF" => false,
    "R64.GETBIT" => false,
    "R64.GETBITARRAY" => false,
    "R64.GETBITS" => false,
    "R64.GETINTARRAY" => false,
    "R64.JACCARD" => false,
    "R64.MAX" => false,
    "R64.MIN" => false,
    "R64.OPTIMIZE" => true,
    "R64.RANGEINTARRAY" => false,
    "R64.SETBIT" => true,
    "R64.SETBITARRAY" => true,
    "R64.SETFULL" => true,
    "R64.SETINTARRAY" => true,
    "R64.SETRANGE" => true,
];
